### ISSUE TITLE
Add `fileLoad` to the config processer

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#1018]
We want to be able to load content of files and parse them directly from the config file:

```yaml
plugin:
  type: 'anything'
  option:
    input: fileLoad('lolz.yml')
```

It should parse `.yml/.yaml/.json` files, otherwise just load it up as text
