### ISSUE TITLE
Cannot set default database name for RethinkDB

### ISSUE THREAD

**Issue by nfsmaniac** [deepstreamIO/deepstream.io#1028]
I am using Deepstream.io v5.0.4 binary for Linux.
My configuration file (config.yml) looks like this
```
storage:
  name: rethinkdb
  options:

    host: localhost
    port: 28015

    database: mydatabase
    defaultTable: mytable

    splitChar: /
```

It's default config + copy & pasted config from Deepstream docs of the RethinkDB connector at the end of file.
First, I realised the [docs](https://deepstream.io/tutorials/plugins/database/rethinkdb/) are outdated. There is `path: rethinkdb`, but I had to change it to `name: rethinkdb`.

But the main problem is -- I can't set default DB name to `mydatabase`. When deepestream server is launched, it always creates a new database called `deepstream` and creates a table called `mytable`.

Is there any syntax change for the `database:` option, as same as for `path:` -> `name:`?
