### ISSUE TITLE
Check client's uid in HTTP auth?

### ISSUE THREAD

**Issue by kyeno** [deepstreamIO/deepstream.io#1092]
Hey,
I have a certain authentication flow that by design should rely on uid()'s quite a bit.

Upon connection and before authentication the client stores it's uid (`deepstream.getUid()`), mangles it and sends it over with few other params to in the `deepstream.login()` object.

Then the auth is redirected to local HTTP `express` server.
I want that HTTP to be aware of the client's Uid and for falseproofing - to fetch it *from the server*, not from the client... but can't find a way. Console logging `connectionData` and `authData` do not give me this information.

I tried "experimenting" a bit with deepstream server's `config.yml` too, but couldn't really find a good documentation for it.

```yaml
  - type: http
    options:
        # a post request will be send to this url on every incoming connection
        endpointUrl: http://127.0.0.1:9387/auth
        # any of these will be treated as access granted
        permittedStatusCodes: [ 200 ]
        # if the webhook didn't respond after this amount of milliseconds, the connection will be rejected
        requestTimeout: 2000
        # promote the following items from the login auth data into headers
        promoteToHeader:
           - token
           - uid
        # the codes which the auth handler should retry. This is useful for when the API you depend on is
        # flaky or going through a not so blue/green deployment
        retryStatusCodes: [ 404, 504 ]
        # the maximum amount of retries before returning a false login
        retryAttempts: 3
        # the time in milliseconds between retries
        retryInterval: 5000
```

The `- uid` is part of my experiment.
How do I achieve this?
