### ISSUE TITLE
Explaination on Info "Heartbeat missing on websocket, terminating connection" 

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io#1095]
I noticed the message "Heartbeat missing on websocket, terminating connection" have being showed up in my server log  for recent days, I would like to understand what does the message suggest for, what should I do to eliminate the message? The deepstream server version: 5.1.8, clientjs version: 5.1.10

**Comment by jaime-ez** [comment]
Hi, whats your server and client config regarding heartBeatInterval ?

**Comment by geohuz** [comment]
@jaime-ez for the server side I didn't make adjustment so I think it's the default value, I'm not sure if this setting block:

```
connectionEndpoints:
  - type: ws-binary
    options:
      # url path websocket connections connect to
      urlPath: /deepstream
      # the amount of milliseconds between each ping/heartbeat message
      heartbeatInterval: 30000
     ....
```

and I don't have a configuration option for the client side,  would you mind to tech me the proper way of doing this on both side?

Thanks!
