### ISSUE TITLE
[Bug] SocketWrapper mismatch in "handlers/record/record-transitions" when storage enabled

### ISSUE THREAD

**Issue by wyl1232792** [deepstreamIO/deepstream.io#1116]
I found this problem when requesting bulk record update via http api, I got a http timeout error on insert, and could always reproduce that. The response says that some records failed to handle, though actually records are successfully inserted since I can see in storage.

version: v6.1.0
client: python.deepstreamio_client (using batch mode)
storage: rethinkdb
cache: redis

https://github.com/deepstreamIO/deepstream.io/blob/117034a674f3fe76942f9c2d72960d9fddd6b117/src/handlers/record/record-transition.ts#L283-L294
Storage could be much slower then cache update, but it is designed to move on to next step at onCacheSetResponse, so basicly write ack is always choosing the wrong wrapper.

**Comment by jaime-ez** [comment]
Hi, after some tests I couldn't reproduce the issue. Please reopen if it persists.

There is a non documented http endpoint parameter `requestTimeout` that defaults to 20000. You can tweak it to avoid this timeout responses:
```
connectionEndpoints:
  - type: http
    options:
      # number of milliseconds before returning an http timeout error. Defaults to 20000
     requestTimeout: 100000
```

Cheers
