### ISSUE TITLE
Support paths for ssl options

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#187]
Users using SSL/HTTPS via configuration can't be expected to copy their entire key into the config file. Support file-paths and synchronous loading at startup instead

```yaml
# SSL Configuration
sslKey: null
sslCert: null
sslCa: null
```
