### ISSUE TITLE
File authentication should contain serverData and clientData

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#304]
File should look as follows:

```
userA:
  password: "tsA+yfWGoEk9uEU/GX1JokkzteayLj6YFTwmraQrO7k=75KQ2Mzm"
  serverData:
    some-optional: "auth-data"
   clientData:  bob
```

Where serverData is used for permissioning, and clientData is sent to the client.
