### ISSUE TITLE
Server config: maxRuleIterations can be non-positive

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#498]
Consider the following simple `conf.yml`:
```yml
permission:
  type: config
  options:
    path: ./permissions.yml
    maxRuleIterations: -1
```
When starting the server, there is no warning or error message with respect to the `maxRuleIterations` value.

Expected behavior:
A warning or an error message because no set of permission rules can be evaluated with a non-positive number of rule iterations.

The behavior was tested with the MacOS standalone binary and the npm version 2.0.1.
