### ISSUE TITLE
ACK_TIMEOUT with Valve permissions, cross references, subscript operator

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#514]
[Zipped demo code](https://github.com/deepstreamIO/deepstream.io/files/674387/subscript-operator.zip)

Consider the following snippet from a Valve file:
```yaml
record:
  "d/$uid":
    create: _('perm/' + user.id)[$uid]
    read:   _('perm/' + user.id)[$uid]
  "*":
    create: true
    write: true
    read: true
    delete: true
    listen: true
```

If the client attempts to get a non-existent record `d/$uid` with, e.g., `client.record.getRecord("d/u101")`, then the server seems to hang, triggering the client's error handler:
```
handleError d/u101 ACK_TIMEOUT R
```
The error can be avoided by removing either line 3 or line 4 from the Valve code above.

**Comment by ChristophConrads-deepstreamHub** [comment]
Simplified demo: [subscript-operator.zip](https://github.com/deepstreamIO/deepstream.io/files/674403/subscript-operator.zip)

`permissions.yml`:
```yml
record:
  "d/*":
    create: _('perm/JohnDoe').boolean
    read:   _('perm/JohnDoe').boolean
  "*":
    create: true
    write: true
    read: true
    delete: true
    listen: true
```
