### ISSUE TITLE
how to restrict field creation within record?

### ISSUE THREAD

**Issue by with0out** [deepstreamIO/deepstream.io#525]
In the example config below, I wish to only allow admin to create fileds within 'chat' record,
and non anonymous users to write to 'chat/msg' field.

But this config would allow creation of any field by users within chat.

```
#config.yml
record:
  "*":
    create: false
    write: false
    read: false
    delete: false
    listen: false
  chat:
    create: "user.data.role === 'admin'"
    write: true
    read: true
    listen: true
  chat/*:
    create: "user.data.role === 'admin'"
    write: "user.data.role === 'admin'"
  chat/msg:
    write: "user.data.role !== 'anonymous'"
```

And if I remove **write: true** in 'chat:', it would disallow writing to 'chat/msg', 
throwing 'MESSAGE_DENIED'.

Maybe I'm not supposed to do this, or is there a way to achieve this?
Thanks!

Edit: I use Redis Cache/Message Connector.
