### ISSUE TITLE
Granular permissioning 'trick' using valve

### ISSUE THREAD

**Issue by RashadSaleh** [deepstreamIO/deepstream.io#623]
Valve does permissioning strictly on the entire record level. This was undesirable for my use case, and - I assume - many other use cases as well. I solved the problem to achieve granular permissioning using valve by "elevating" the basic unit of storage from a record to a table: instead of a table of, say, users, you get a table per user. Now, your permissioning file might look like this:

```yml
record:
  "*":
    create: false
    write: false
    read: false
    delete: false
    listen: false
  "$uid/*":
    write: "user.data.id === $uid"
    read: "user.data.id === $uid"
    create: "user.data.role === 'admin'"
  "$uid/public_profile":
    read: true
```

To my knowledge, permissioning with the table name as a variable is not found anywhere in the documentation, possibly because the creators haven't considered it. But it works -- at least with the basic tests I've done so far. More robust tests are required and/or the insight of the original developers. Also, I am not sure how this would work with the search functionality, but I'll keep you updated.

Good luck everyone.
