### ISSUE TITLE
Message denied on permission with string containing '/' character

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#672]
I am using rethinkdb search provider and have configured valve permissions to restrict searching some tables to certain user roles.

Snippet of permissions.yml:
```
record:
  'search?$queryString': # restricted tables can only be requested by user with role server or admin
    create: '(["log", "user"].indexOf($queryString.match(/"table":"(.*?)"/)[1]) == -1) || (["server", "admin"].indexOf(user.data.role) > -1)'
    write: 'user.data.role === "server"'
    delete: 'user.data.role === "server"'
    read: '(["log", "user"].indexOf($queryString.match(/"table":"(.*?)"/)[1]) == -1) || (["server", "admin"].indexOf(user.data.role) > -1)'
    listen: 'user.data.role === "server"'
```

Above valve permission works well for queryString such as:
```
const query = {
    table: 'user',
    query: true
}
```
But for the following query, deepstream returns message denied eventhough the table is not in the restricted list and even when the user has admin role:
```
const query = {
        table: 'product',
        query: [
            ['categoryId', 'match', 'category/abc123']
        ]
    }
```
If I remove the '/' character, then I no longer gets message denied. 
What have I done wrong?

**Comment by layanto** [comment]
Even if I set the permissions to true (as below), I still get ["MESSAGE_DENIED", "search?{"table": "product", "query": [["categoryId", "match", "category/abc123"]]}", "C"] "MESSAGE_DENIED" "R"

```
record:
  'search?$queryString': # restricted tables can only be requested by user with role server or admin
    create: true
    write: 'user.data.role === "server"'
    delete: 'user.data.role === "server"'
    read: true
    listen: 'user.data.role === "server"'
```

**Comment by layanto** [comment]
I have also tried to escape the regex pattern as follows but still getting MESSAGE_DENIED.
```
const query = {
        table: 'product',
        query: [
            ['categoryId', 'match', '^category\/abc123']
        ]
    }
```

**Comment by layanto** [comment]
@yasserf is this a bug or have I done​ something wrong?

**Comment by yasserf** [comment]
hey @layanto, it looks correct to me. Will mark as a bug so we can put it through our QA and let you know!

**Comment by AlexBHarley** [comment]
This is fixed on master:

permissions.yml
```
record:
  ...
  'search?$queryString': # restricted tables can only be requested by user with role server or admin
    create: '(["log", "user"].indexOf($queryString.match(/"table":"(.*?)"/)[1]) == -1) || (["server", "admin"].indexOf(user.data.role) > -1)'
    write: 'user.data.role === "server"'
    delete: 'user.data.role === "server"'
    read: '(["log", "user"].indexOf($queryString.match(/"table":"(.*?)"/)[1]) == -1) || (["server", "admin"].indexOf(user.data.role) > -1)'
    listen: 'user.data.role === "server"'
...
```

users.yml

```
userA:
  password: "rCOSZxJrgze2AZdVQh12c6ErDMOG0M+Rx5Yu7S5d91c=GS4SbTQYmoaGwjm2shEobg=="
  serverData:
    role: admin
```

And ran the script
```
const deepstream = require('deepstream.io-client-js')

const client = deepstream('localhost:6020')
client.login({ username: 'userA', password: 'password' })

const query = {
    table: 'product',
    query: [
        ['categoryId', 'match', '^category\/abc123']
    ]
}

const record = client.record.getRecord(`search?${JSON.stringify(query)}`)
record.whenReady(() => console.log(record.get()))
```

And the following is printed out:

```
{}
```
