### ISSUE TITLE
Checking for the existence of a record causes an infinite loop when read permissions rely on oldData

### ISSUE THREAD

**Issue by jpbecotte** [deepstreamIO/deepstream.io#730]
The files are here: [issue.zip](https://github.com/deepstreamIO/deepstream.io/files/1086839/issue.zip)

Using the following permissions:
````
record:
    "*":
        read: "oldData.xyz === 3"
        create: true
        write: true
        delete: true
        listen: true

event:
    "*":
        publish: true
        subscribe: true
        listen: true

rpc:
    "*":
        provide: true
        request: true

presence:
    "*":
        allow: true
````

Now if you look at the client.js file (line 13), the callback passed to `record.has` is never invoked. If you remove, in the permissions file `read: "oldData.xyz === 3"` with `read: true`, it'll work as expected.
````javascript
const deepstream = require('deepstream.io-client-js');
const client = deepstream('localhost:6020');

client.on('error', (error) => {
  console.log('--- Deepstream error: ', error);
});

client.login({
  username: "userA",
  password: "password",
}, () => {
  console.log('before record.has');
  client.record.has('someRecordThatDoesNotExists', (error, exists) => {
    if (error) console.log(error);
    console.log('after record.has, returned value: ', exists);
  });
});
````
After making some researches in the source code, in `permission/rule-applications.js`, `_getArguments()` will always trigger a `recordRequest`. This causes `_onLoadComplete` to set `this._runScheduled = true`, thus making `_run`to loop indefinitely. I don't know if this may help or not.
