### ISSUE TITLE
https://deepstream.io/docs/server/user-file/ is out of date

### ISSUE THREAD

**Issue by reactor81** [deepstreamIO/deepstream.io#740]
I've been able to setup a working users.json file, and the password is working, and I can use user.id in my permissions.yaml. 

However user.data always seems to be null, so I get an auth error: 
```
MESSAGE_PERMISSION_ERROR | error when executing function anonymous(_,user,data,oldData,now,action
/**/) {
return user.clientData.role === 'admin';
}
for [object Object]: TypeError: Cannot read property 'role' of undefined

```

My users.json (I also tried a users.yml with same settings, but that also did not work) looks like:
```
{
    "myadminname": {
        "password": "mypass",
        "data": { "role": "admin" },
    },
    "user": {
        "password": "myuserpass",
        "data": { "role": "user" },
    }
}

```
Same with a yaml version as below:
```
myusername:
  password: "mypass"
  data:
    role: admin
user:
  password: "myuserpass"
  data:
    role: user
```

Any ideas on why this error might be happening?
