### ISSUE TITLE
Socket hangs up most of the time

### ISSUE THREAD

**Issue by kamerk22** [deepstreamIO/deepstream.io#816]
@AlexBHarley 
## Use Case

I have nodejs application which will handle all subscription logic and have API in php application. whenever something changed my php application emit the event to deepstream and nodejs handle it.

Problem comes when I added authentication server. So my deepstream conf having following.

```yaml
serverName: UUID
showLogo: true
logLevel: DEBUG
libDir: /var/lib/deepstream
sslKey: null
sslCert: null
sslCa: null
connectionEndpoints:
  websocket:
    name: uws
    options:
      port: 6020
      host: 0.0.0.0
      urlPath: /deepstream
      healthCheckPath: /health-check
      heartbeatInterval: 30000
      outgoingBufferTimeout: 0
      unauthenticatedClientTimeout: 180000
      maxAuthAttempts: 3
      logInvalidAuthData: false
      maxMessageSize: 1048576
  http:
    name: http
    options:
      port: 7000
      host: 0.0.0.0
      allowAuthData: false
      enableAuthEndpoint: false
      authPath: /auth
      postPath: /
      getPath: /
      healthCheckPath: /health-check
      allowAllOrigins: true
      origins:
        - localhost
        - 192.168.1.23
        - 'http://192.168.1.23'
logger:
  name: default
  options:
    colors: true
    logLevel: INFO
storageExclusion: null
auth:
  type: http
  options:
    endpointUrl: 'http://192.168.1.23/api/isvalid'
    permittedStatusCodes:
      - 200
    requestTimeout: 10000
permission:
  type: config
  options:
    path: ./permissions.yml
    maxRuleIterations: 3
    cacheEvacuationInterval: 60000
rpcAckTimeout: 1000
rpcTimeout: 10000
cacheRetrievalTimeout: 1000
storageRetrievalTimeout: 2000
dependencyInitialisationTimeout: 2000
listenResponseTimeout: 500
lockTimeout: 1000
lockRequestTimeout: 1000
broadcastTimeout: 0
```

![capture](https://user-images.githubusercontent.com/11503211/31596903-fc48c88a-b262-11e7-8a34-c341cb0c6732.PNG)

I need to run deepstream built-in API server for php client as mentioned and also need a authentication handler which leads to socket hangs up situation.
I have also increased the `requestTimeout` option but still I'm facing same problem.
Any Idea how can I solve this or any better solution for my use case. Thank you

**Comment by EnglishAdam** [comment]
I have just upgrade from 3.0.0 to 3.1.0 and I'm experiencing the same/similar problem. I am unable to authenticate users via http anymore and receive the following log, despite the authentication working prior to the upgrade:

`...`
`INFO | Deepstream started`
`INCOMING_CONNECTION | from undefined (192.168.1.76)`
`AUTH_ERROR | http auth error: Error: socket hang up`
`INVALID_AUTH_DATA | invalid authentication data: {"username":"<username>", ...}`

**Comment by EnglishAdam** [comment]
The authentication request.

**Comment by EnglishAdam** [comment]
@AlexBHarley Testing it again, I believe the issue is the authentication request. The authentication POST request is no longer sent to my web-hook URL. 

Thanks.

**Comment by kamerk22** [comment]
@AlexBHarley  
Any updates??

**Comment by AlexBHarley** [comment]
Took a look into this. It looks like @kamerk22 you're using http auth via the http api and @EnglishAdam is using it via a websocket client.

I had the following deepstream (`v3.1.0`) config:

```
auth:
  type: http
  options:
    endpointUrl: localhost:3000/login
    permittedStatusCodes: [ 200 ]
    requestTimeout: 2000
...
 connectionEndpoints:
  websocket:
    name: uws
    options:
        port: 6020
        host: 0.0.0.0
        urlPath: /deepstream
        healthCheckPath: /health-check
        heartbeatInterval: 30000
        outgoingBufferTimeout: 0

        unauthenticatedClientTimeout: 180000
        maxAuthAttempts: 3
        logInvalidAuthData: false
        maxMessageSize: 1048576

  http:
    name: http
    options:
      port: 8080
      host: 0.0.0.0
      allowAuthData: true
      enableAuthEndpoint: true
      authPath: /auth
      postPath: /
      getPath: /
      healthCheckPath: /health-check
      allowAllOrigins: true
      origins: []
```

I was only able to reproduce the `AUTH_ERROR | http auth error: Error: socket hang up` error by having my webhook not respond within the `requestTimeout`.

For reference my auth server is in node js and looks as follows:

```
const express = require('express')
const bodyParser = require('body-parser')
const app = express()

app.use(bodyParser.json())

app.post('/login', (req, res) => {
  if (req.body.authData.username === 'alex@test.com') {
    res.json({
      username: 'chris',
      clientData: { themeColor: 'pink' },
      serverData: { role: 'admin' }
    })
  } else {
    res.status(403).send('Invalid Credentials')
  }
})

app.listen(3000, () => {
  console.log('Auth server listening on localhost:3000')
})
```

Are there any extra steps I can take to reproduce this?
