### ISSUE TITLE
Authenticated providers but open clients

### ISSUE THREAD

**Issue by rahil471** [deepstreamIO/deepstream.io#890]
Hello, 

How can I implement a provider that is basically a client which has permissions to write/modify records/ lists and consumers that are clients that can only read records/lists. 

I'm aware of authentication and permissions. At the moment I'm using file-based authentication. The problem is that once I add a user as provider in my config; open authentication stops working, so I have to create another user for consumer clients as `consumer`. 

In an ideal situation I want the providers to login with `username` and `password` but keep open authentication(no need for username and password) for any other clients who wants to listen to streams. 

```
# Username
rahil:
  # Password hash ( hash options passed within config.yml )
  # This hash represents clear text "password" with default options
  password: "hash"
  # Server data is used within your permission handler
  serverData:
    someOptional: "auth-data"
    role: "provider"
  # Client data is sent to the client on login
  clientData:
    favouriteColor: "red"
consumer:
  password: 'hash'
```

```
presence:
  "*":
    allow: true
record:
  "*":
    create: true
    write: 'user.data.role === "provider"'
    read: true
    delete: true
    listen: true
event:
  "*":
    publish: true
    subscribe: true
    listen: true
rpc:
  "*":
    provide: true
    request: true

```
