### ISSUE TITLE
Server does not block client on failed authentication

### ISSUE THREAD

**Issue by samuk159** [deepstreamIO/deepstream.io#928]
Hi, im trying to use JWT authentication with deepstream opensource (local server). However when authentication fails (for exemple, if i just call login() without parameters) the client is not "blocked" and is able to publish and subscribe. The expected behavior would be the client throwing an exception or at least not being able to pub/sub. Maybe i need to explicitly disable open auth on the config.yml? If so how can i do this? Thank you.

Client code (JS):
```javascript
let ds = deepstream('localhost:6020').login();

ds.event.subscribe("test", res => { 
  console.log(res);
});

ds.event.emit("test", "message");
```
config.yml auth:
```yml
auth:
  # type: none

#   # reading users and passwords from a file
#   type: file
#   options:
#     # Path to the user file. Can be json, js or yml
#     path: ./users.yml
#     # the name of a HMAC digest algorithm
#     hash: 'md5'
#     # the number of times the algorithm should be applied
#     iterations: 100
#     # the length of the resulting key
#     keyLength: 32

# getting permissions from a http webhook
  type: http
  options:
    # a post request will be send to this url on every incoming connection
    endpointUrl: http://localhost:9080/check-token
    # any of these will be treated as access granted
    permittedStatusCodes: [ 200 ]
    # if the webhook didn't respond after this amount of milliseconds, the connection will be rejected
    requestTimeout: 2000
```

**Comment by valentinvichnal** [comment]
Hi, you must authenticate clients with login(), but after that you can set roles to every authenticated client.

A simple authorization example to set every client who provide wrong JWT data a "guest" role:
```js
.post('check-token', function (request, reply) {

  verifyJWT(token, (err, tokenData) => {
    if (err) {
      log.error('incorrect.token');
      // set the client Guest role

      const authorizationData = {
        userId: 'guest-random-number', // must be unique
        clientData: { role: 'GUEST' },
        serverData: { role: 'GUEST' }
      };

      reply.send(authorizationData);
    }

    log.info('correct.token');
    // set the client User role

    // you can also set custom rights
    let isAdmin = false;
    let isBanned = false;

    const authorizationData = {
      userId: tokenData.userId,
      clientData: { role: 'USER', userId: userId, admin: isAdmin },
      serverData: { role: 'USER', userId: userId, admin: isAdmin }
    };

    reply.send(authorizationData);

  });

}
```

You can configure the permissions in the deepstream folder `conf/permissions.yml`:

To make it simple allow record modification and RPC calls only for Users, reading public records for both Users and Guests, reading private records only for that specific user.
You can create custom RPC calls that can be called only by Guests.
```yml
record:
  "*":
    create: "user.data.role && user.data.role === 'USER'"
    write: "user.data.role && user.data.role === 'USER'"
    read: true
    delete: false
    listen: "user.data.role && user.data.role === 'USER'"
  # PRIVATE
  "profile/$userId":
    create: "user.data.role && user.data.role === 'USER'"
    write: "user.data.role && user.data.role === 'USER'"
    read: "user.data.role && user.data.role === 'USER' && user.id === $userId"
rpc:
  "guestfunction":
    provide: "user.data.role && user.data.role === 'SERVER'"
    request: "user.data.role && user.data.role === 'GUEST'"
```
