### ISSUE TITLE
Cant run with LetsEncrypt SSL cert

### ISSUE THREAD

**Issue by zveljkovic** [deepstreamIO/deepstream.io#941]
I have tried Ubuntu install (v3.2.3) and Docker version (v3.2.2). I get the error below which I identified comes from uWebSockets library. My guess would be loading cert files as strings and passing those to uWS which tries to load those as paths.

```INFO | State transition (services-started): ServiceInit -> ConnectionEndpointInit
(node:29066) UnhandledPromiseRejectionWarning: App construction failed
(node:29066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PLUGIN_ERROR | connectionEndpoint wasn't initialised in time
/etc/deepstream/src/utils/dependency-initialiser.js:94
    throw error
    ^

Error: connectionEndpoint wasn't initialised in time
    at DependencyInitialiser._onTimeout (/etc/deepstream/src/utils/dependency-initialiser.js:92:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)```


Config
# SSL Configuration
sslKey: /etc/letsencrypt/live/nonp-deepstream.dsgapps.dk/privkey.pem
sslCert: /etc/letsencrypt/live/nonp-deepstream.dsgapps.dk/fullchain.pem
sslDHParams: /etc/deepstream/dhparam4096.pem
#sslPassphrase: null

**Comment by zveljkovic** [comment]
Also this error is shown if I use longer dependencyIntializationTimeout

```
(node:1) UnhandledPromiseRejectionWarning: App construction failed
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yasserf** [comment]
Can you please try with v3.1.6? We are using a new uWS engine in v3.2 and still a couple kinks to iron out.

**Comment by zveljkovic** [comment]
Hi, I have tried with the v3.1.0 via Docker and it worked. Docker had only v3.1.0 in v.3.1.X.

For anyone stumbling here, I solved this with the Nginx as reverse proxy and terminating HTTPS there.
Below is the Nginx config (/etc/nginx/nginx.conf) for this as I had some issues with the one from the site 
```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
      server localhost:6020;
    }
    upstream httpendpoint {
      server localhost:8080;
    }

    server {
       listen 443 ssl;
       ssl_certificate /etc/letsencrypt/live/YOUR_DOMAIN_HERE/fullchain.pem;
       ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN_HERE/privkey.pem;
       ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
       ssl_ciphers         HIGH:!aNULL:!MD5;


       # Deepstream websocket redirect
       location /deepstream {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            rewrite ^(.*) $1 break; # Had a problem here with location been rewritten as /deepstream/deepstream and not fitting the deepstream config var /deepstream
       }

      # Deepstream http endpoint
      location /http {
           proxy_pass http://httpendpoint;
           proxy_http_version 1.1;
           rewrite ^/http(.*) $1 break;
      }
   }
}
```

**Comment by yasserf** [comment]
Yeah using nginx or any reverse proxy is definitely the recommended approach.

Can you point me to where you get/create letsencrypt ssl certs so I can test locally?

**Comment by yasserf** [comment]
hello! Any chance you can provide those details? Would love to try it out before getting the 4.0 release out. Thanks!

**Comment by zveljkovic** [comment]
Hi, sorry for late response, I haven't seen the earlier message. You dont need to use LetsEncrypt certs, you can use self signed certificate (ie. generated here http://www.selfsignedcertificate.com/). If you are on windows you need to convert the certificate to p7b format (please try these https://www.rapidsslonline.com/ssl-tools/ssl-converter.php) and install into Trusted Root Certificate store. Also restart Chrome, to pick up new cert and prevent self signed cert warnings. I assume everything will work even with warnings on browser side.

**Comment by yasserf** [comment]
Sweet thanks, will try out 👍

**Comment by lyollix** [comment]
I use 3.2.4 on master and 
have the same error as in the first comment.

When I fix this,  all work ok
src/config/config-initialiser.js
function handleSSLProperties (config) {
...
   ---    config[key] = fs.readFileSync(resolvedFilePath, 'utf8')
   +++ config[key] = resolvedFilePath
}

server = new uWS.SSLApp(...) want only files names

**Comment by layanto** [comment]
> Yeah using nginx or any reverse proxy is definitely the recommended approach.
> 
> Can you point me to where you get/create letsencrypt ssl certs so I can test locally?

I have used this in the past - https://github.com/Neilpang/acme.sh
Shell script to get new letsencrypt ssl certificate and periodically update the certificate prior to expiry.

**Comment by yasserf** [comment]
This has been changed now btw

SSL config is no longer a deepstream thing, its specific to whatever connection endpoint

Also, you use can now use this syntax in config files:

```
sslFIle: file(./sslFile)
```

which will then normalize the path so that it finds everything relative to the config file (important when running a global install / different paths)

**Comment by yasserf** [comment]
So for example:

```
connectionEndpoints:
  - type: uws-websocket
    options:
        # port for the websocket server
        port: 6020
        # host for the websocket server
        host: 0.0.0.0
        # url path websocket connections connect to
        urlPath: /deepstream
        # url path for http health-checks, GET requests to this path will return 200 if deepstream is alive
        healthCheckPath: /health-check
        # the amount of milliseconds between each ping/heartbeat message
        heartbeatInterval: 30000
        # the amount of milliseconds that writes to sockets are buffered
        outgoingBufferTimeout: 50
        # the maximum amount of bytes to buffer before flushing, stops the client from large enough packages
        # to block its responsivness
        maxBufferByteSize: 100000

        # Headers to copy over from websocket
        headers:
          - user-agent

        # Security
        # amount of time a connection can remain open while not being logged in
        unauthenticatedClientTimeout: 180000
        # invalid login attempts before the connection is cut
        maxAuthAttempts: 3
        # if true, the logs will contain the cleartext username / password of invalid login attempts
        logInvalidAuthData: false
        # maximum allowed size of an individual message in bytes
        maxMessageSize: 1048576

        # SSL Configuration
        sslKey: null
        sslCert: null
        sslDHParams: null
        sslPassphrase: null
```

I still need to fix those up in the actual connection endpoints. I just don't have any SSL certs to test them with. If anyone is willing to try it out and raise a PR I would be extremely grateful!

**Comment by crapthings** [comment]
just use this to get ssl to test ?

openssl req -nodes -new -x509 -keyout server.key -out server.cert

**Comment by thorsby** [comment]
Had to get Deepstream SSL working to test out WebRTC examples (browser getUserMedia requires content to be served from HTTPS which then requires the WebSocket to be WSS)

>         # SSL Configuration
>         sslKey: null
>         sslCert: null
>         sslDHParams: null
>         sslPassphrase: null

The above options are incorrect. 

https://github.com/deepstreamIO/deepstream.io/blob/master/src/connection-endpoint/uws/connection-endpoint.ts
Looking through endpoint source , I picked up that options are named keyFileName and certFileName instead of ~~sslKey~~ and ~~sslCert~~

This makes Deepstream provide a functional WSS. This however not indicated from INFO messages when starting DS, could be nice.

By the way, with a self-signed certificate, browser is gonna refuse the connection (even though same certificate is already bypassed for the content on same hostname). This can be overcome by browsing to https://localhost:6020/deepstream and bypassing it there.

**Comment by yasserf** [comment]
I will try get the options documented in V5, as it supports file lookups

**Comment by yasserf** [comment]
@thorsby hey! Would you by any chance be open to adding this as a PR to V5?

The new HTTP Service means you can configure ssl in one place and it should work everywhere, ideally we would just need the following:

```
httpServer:
  type: default
  options:
    key: loadFile("/srv/www/keys/my-site-key.pem"),
    cert: loadFile("/srv/www/keys/chain.pem")
  
  type: uws
  options:
    keyFileName: file(...) // gets file name relative to config file if not absolute
    certFileName: file(...) 
```

**Comment by yasserf** [comment]
This has been added now in V5!

```yaml
httpServer:
  type: default
  options:
    # url path for http health-checks, GET requests to this path will return 200 if deepstream is alive
    healthCheckPath: /health-check
    # -- CORS --
    # if disabled, only requests with an 'Origin' header matching one specified under 'origins'
    # below will be permitted and the 'Access-Control-Allow-Credentials' response header will be
    # enabled
    allowAllOrigins: true
    # a list of allowed origins
    origins:
      - 'https://example.com'
    # Headers to copy over from websocket
    headers:
      - user-agent
    # Options required to create an ssl app
    # ssl:
    #   key: fileLoad(ssl/key.pem)
    #   cert: fileLoad(ssl/cert.pem)
    #   ca: ...
    
  # type: uws
  # options:
  #   # url path for http health-checks, GET requests to this path will return 200 if deepstream is alive
  #   healthCheckPath: /health-check
  #   # Headers to copy over from websocket
  #   headers:
  #     - user-agent
  #   # Options required to create an ssl app
  #   # ssl:
  #   #   key: file(ssl/key.pem)
  #   #   cert: file(ssl/cert.pem)
  #   ##  dhParams: ...
  #   ##  passphrase: ...
```
